### PR TITLE
Stable : Edit error...

### PR DESCRIPTION
**Pull request by wahrani**
When I try to edit a page on ar.wikipedia.org from toolabs, I get this error :

 API Error...

Badtoken detected retrying with new tokens...

API Error...

Code: badtoken
Text: Invalid token

Edit error...

Any solution ...

### CODE REVIEW

**Comment by cyberpower678** [comment]
Try deleting your cookies.  You seem to have a bad one there.

**Comment by wahrani** [comment]
I delete it, but the no change.

after some investigations, I think that we must update wiki::get_tokens function to use (action => 'query',  'meta'   => 'tokens') in stead of ('action' => 'tokens')

**Comment by cyberpower678** [comment]
I guarantee you that is not the problem.  You did restart your bot afterwards correct?

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by wahrani** [comment]
Always the same error

**Comment by cyberpower678** [comment]
So I have not been able to replicate the error.

**Comment by wahrani** [comment]
Can you make some edit on articles ( namespace = 0) on ar.wikipedia.org ?

**Comment by addshore** [comment]
Whats the status of this PR? it looks odd (as in there are no changes...?)

**Comment by wahrani** [comment]
[Solved] by changing the protocol to HTTPS

**Pull request closed without merging**
